apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath
spec:
  selector:
    matchLabels:
      app: hostpath
  template:
    metadata:
      labels:
        app: hostpath
    spec:
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: aws-ebs
          awsElasticBlockStore:
            volumeID: volumeId
      containers:
      - name: hostpath
        volumeMounts:
          - mountPath: /var/log
            name: var-log
            readOnly: true
        image: busybox
        command:
          - "sleep"
          - "3600"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
