apiVersion: v1
kind: Pod
metadata:
  name: green
  labels:
    app: green
    environment: test
spec:
  containers:
  - name: green
    image: amigoscode/kubernetes:green
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: labels-and-selector
spec:
  selector:
    app: green
    environment: test
  ports:
  - port: 80
    targetPort: 80

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   namespace: kube-system
#   name: green
#   labels:
#     app: green
#     environment: test
# spec:
#   containers:
#   - name: green
#     image: amigoscode/kubernetes:green
#     resources:
#       limits: 
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80

# --- 

# apiVersion: v1
# kind: Service
# metadata:
#   name: labels-and-selector
# spec:
#   selector:
#     app: green
#     environment: test
#   ports:
#   - port: 80
#     targetPort: 80
