apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
spec:
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      volumes:
        # create a name to bind with VolumeMounts 
        - name: secret-1
          secret:
            secretName: mysecret
      containers:
      - name: secrets
        image: busybox
        volumeMounts:
          - mountPath: /etc/secrets
            name: secret-1
        env:
          - name: AMIGOSCODE_SECRET
            valueFrom:
              secretKeyRef:
                key: secret
                name: mysecret-from-file
        command:
          - "sleep"
          - "3600"
        resources:
          limits: 
            memory: "128Mi"
            cpu: "500m"
 
        
